import type { Metadata } from "next";
import "./globals.css";
import LoadingWrapper from "@/components/LoadingWrapper";
import AuthGuard from "@/components/AuthGuard";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <div className="w-full h-dvh">
          <AuthGuard>
            <LoadingWrapper delay={2000}>
              {children}
            </LoadingWrapper>
          </AuthGuard>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
